name: Termux Script Runner

on:
  workflow_dispatch:

jobs:
  termux-test:
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'  # Use Azul Zulu JDK for compatibility      

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'  # Use Azul Zulu JDK for compatibility
              
      - name: Install Android SDK components
        run: |
          echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --licenses
          $ANDROID_HOME/tools/bin/sdkmanager --channel=3  # Enable legacy channel
          $ANDROID_HOME/tools/bin/sdkmanager "platform-tools" "emulator" "platforms;android-25"
          $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-25;default;armeabi-v7a"
          
      - name: Start ARM Emulator
        uses: licy183/android-emulator-runner@v2.27.0.1
        with:
          api-level: 25
          arch: armeabi-v7a
          profile: Nexus 5
          emulator-options: |
            -no-window
            -gpu swiftshader_indirect
            -noaudio
            -no-boot-anim
            -memory 2048
          script: |
            adb wait-for-device
            adb shell settings put global window_animation_scale 0
            adb shell settings put global transition_animation_scale 0

      - name: Install Termux
        run: |
          wget -q https://f-droid.org/repo/com.termux_1020.apk -O termux.apk
          adb install -g termux.apk
          adb shell pm grant com.termux android.permission.READ_EXTERNAL_STORAGE
          adb shell pm grant com.termux android.permission.WRITE_EXTERNAL_STORAGE
   
      - name: Push Script
        run: |
          adb push sm64coopdx.sh /data/data/com.termux/files/home/

      - name: Run Script
        run: |
          adb shell am startservice -n com.termux/com.termux.app.RunCommandService \
            -a com.termux.RUN_COMMAND \
            --es com.termux.RunCommandService.COMMAND_PATH "./sm64coopdx.sh" \
            --ez com.termux.RunCommandService.BACKGROUND "false"
            
      - name: Get Build Results
        run: |
          adb pull /data/data/com.termux/files/home/sm64coopdx/build/us_pc/sm64coopdx.apk || echo "APK not found; continuing..."

      - name: Upload APK Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sm64coopdx.apk
          path: sm64coopdx.apk
          if-no-files-found: warn
