name: Build Termux with Preinstalled Bootstraps

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Termux repository
        run: |
          git clone https://github.com/termux/termux-app.git
          cd termux-app
          git checkout v0.119.0-beta.1  # Checkout the specific tag

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Ensure compatibility with Termux

      - name: Set up Android SDK
        uses: actions/setup-android@v2
        with:
          sdk-version: '30.0.3'  # Adjust SDK version
          ndk-version: '21.3.6528147'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-11-jdk \
            git \
            python3 \
            wget \
            unzip \
            curl

      - name: Generate script to install standard bootstraps
        run: |
          # Create script to install the default bootstrap
          echo "Creating bootstrap installation script..."
          echo '#!/data/data/com.termux/files/usr/bin/bash' > termux-init.sh
          echo 'apt update' >> termux-init.sh
          echo 'apt install -y termux-tools' >> termux-init.sh
          echo 'apt install -y python wget git make build-essential' >> termux-init.sh
          echo 'apt clean' >> termux-init.sh
          chmod +x termux-init.sh
          
          # Place the script in the appropriate directory to run on boot
          mkdir -p /data/data/com.termux/files/usr/etc/init.d/
          mv termux-init.sh /data/data/com.termux/files/usr/etc/init.d/

      - name: Build Termux APK
        run: |
          cd termux-app
          ./gradlew build

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: termux-apk
          path: termux-app/app/build/outputs/apk/debug/*.apk
