name: SM64CoopDX Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: termux/termux-docker:x86_64

    steps:
      - name: Prepare Environment
        run: |
          # Install essential packages
          pkg update -y
          pkg install -y git make clang python zip

      - name: Clone Your Repository
        run: |
          git clone https://github.com/$GITHUB_REPOSITORY.git my-repo

      - name: Clone SM64CoopDX
        run: |
          git clone --recursive https://github.com/ManIsCat2/sm64coopdx.git

      - name: Copy baserom
        run: |
          cp my-repo/baserom.us.z64 sm64coopdx/

      - name: Build ROM
        run: |
          cd sm64coopdx
          make -j$(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sm64-build
          path: sm64coopdx/build