name: Run Termux in Android Emulator

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ADB
        run: |
          sudo apt-get update
          sudo apt-get install -y adb

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Download Termux APK
        run: wget https://f-droid.org/repo/com.termux_1020.apk -O termux.apk

      - name: Start Android Emulator, Install Termux, and Run Script
        uses: reactivecircus/android-emulator-runner@v2.33.0
        with:
          api-level: 28
          script: |
            adb start-server
            adb devices

            # Install Termux
            adb install termux.apk

            # Grant storage permissions
            adb shell pm grant com.termux android.permission.WRITE_EXTERNAL_STORAGE

            # Launch Termux
            adb shell am start -n com.termux/.HomeActivity
            sleep 5

            # Set up storage
            adb shell input touchscreen text "termux-setup-storage"
            adb shell input keyevent 66
            sleep 3

            # Push files to shared storage
            adb push baserom.us.z64 /sdcard/
            adb push setup_build.sh /sdcard/
            sleep 2

            # Execute commands in Termux (properly formatted)
            adb shell input touchscreen text "mv\ /sdcard/baserom.us.z64\ \~/"
            adb shell input keyevent 66
            sleep 2
            
            adb shell input touchscreen text "mv\ /sdcard/setup_build.sh\ \~/"
            adb shell input keyevent 66
            sleep 2
            
            adb shell input touchscreen text "chmod\ +x\ \~/setup_build.sh"
            adb shell input keyevent 66
            sleep 2
            
            adb shell input touchscreen text "./setup_build.sh"
            adb shell input keyevent 66
            sleep 300

      - name: Get Build Results
        run: |
          adb pull /data/data/com.termux/files/home/sm64coopdx/build/us_pc/sm64coopdx.apk || echo "APK not found"

      - name: Upload APK Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sm64coopdx.apk
          path: sm64coopdx.apk
          if-no-files-found: warn