name: Termux SM64CoopDX Build

on: [push, pull_request]

jobs:
  termux-build:
    runs-on: ubuntu-latest
    container:
      image: termux/termux-docker:x86_64
      volumes:
        - ${{ github.workspace }}:/home/termux/work
    steps:
      - name: Install Dependencies
        run: |
          pkg update -y
          pkg remove -y libglvnd
          pkg install -y git wget make python getconf zip \
                         apksigner clang binutils libglvnd-dev aapt which nodejs

      - name: Checkout Repository
        run: |
          cd /home/termux/work
          git config --global --add safe.directory /home/termux/work
          git fetch origin $GITHUB_REF
          git checkout -qf $GITHUB_SHA

      - name: Checkout SM64CoopDX
        run: |
          cd /home/termux
          git clone --recursive https://github.com/ManIsCat2/sm64coopdx.git

      - name: Copy baserom.us.z64
        run: |
          cp /home/termux/work/baserom.us.z64 /home/termux/sm64coopdx/baserom.us.z64

      - name: Build SM64CoopDX
        run: |
          cd /home/termux/sm64coopdx
          make -j$(nproc)

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sm64coopdx-build
          path: /home/termux/sm64coopdx/build