name: Run Termux in Android Emulator

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ADB
        run: |
          sudo apt-get update
          sudo apt-get install -y adb

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Download Termux APK
        run: wget https://f-droid.org/repo/com.termux_1020.apk -O termux.apk

      - name: Start Android Emulator, Install Termux, and Run Script
        uses: reactivecircus/android-emulator-runner@v2.33.0
        with:
          api-level: 28
          script: |
            adb start-server
            adb devices

            # Install Termux
            adb install termux.apk

            # Grant storage permissions (Android 9/API 28)
            adb shell pm grant com.termux android.permission.WRITE_EXTERNAL_STORAGE

            # Launch Termux and set up storage
            adb shell am start -n com.termux/.HomeActivity
            sleep 5  # Wait for Termux to launch

            # Execute termux-setup-storage within Termux
            adb shell input text "termux-setup-storage"
            adb shell input keyevent 66  # Send Enter key
            sleep 3  # Wait for storage setup

            # Push files to shared storage
            adb push baserom.us.z64 /storage/emulated/0/
            adb push setup_build.sh /storage/emulated/0/
            sleep 2  # Ensure files transfer

            # Execute commands in Termux to move files and run build
            adb shell input text "mv ~/storage/shared/baserom.us.z64 ~/ && \
              mv ~/storage/shared/setup_build.sh ~/ && \
              chmod +x ~/setup_build.sh && \
              ./setup_build.sh"
            adb shell input keyevent 66  # Send Enter key
            sleep 60  # Initial build time

            # Keep the emulator running while build completes
            while [ ! -f /data/data/com.termux/files/home/build_log.txt ]; do
              sleep 30
              adb shell input keyevent 82  # Keep screen awake
            done

      - name: Retrieve Termux Build Log
        run: |
          adb pull /data/data/com.termux/files/home/build_log.txt || echo "No log found"

      - name: Upload Termux Build Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: termux-build-log
          path: build_log.txt
          if-no-files-found: warn

      - name: Get Build Results
        run: |
          adb pull /data/data/com.termux/files/home/sm64coopdx/build/us_pc/sm64coopdx.apk || echo "APK not found"

      - name: Upload APK Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sm64coopdx.apk
          path: sm64coopdx.apk
          if-no-files-found: warn