name: Run Termux in Docker

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: termux/termux-docker:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Termux and Install Dependencies
        run: |
          apt update && apt upgrade -y
          apt install -y git wget make python zip clang binutils

      - name: Push Files to Termux Home
        run: |
          cp baserom.us.z64 /data/data/com.termux/files/home/
          cp setup_build.sh /data/data/com.termux/files/home/
          chmod +x /data/data/com.termux/files/home/setup_build.sh

      - name: Run Setup Script
        run: |
          cd /data/data/com.termux/files/home
          ./setup_build.sh

      - name: Get Build Results
        run: |
          ls /data/data/com.termux/files/home/sm64coopdx/build/us_pc/ && echo "Build directory exists" || echo "Build directory NOT found!"
          ls /data/data/com.termux/files/home/sm64coopdx/build/us_pc/sm64coopdx.apk && echo "APK found!" || echo "APK NOT found!"

      - name: Upload APK Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sm64coopdx.apk
          path: /data/data/com.termux/files/home/sm64coopdx/build/us_pc/sm64coopdx.apk
          if-no-files-found: warn