name: Run Termux in Android Emulator

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ADB
        run: |
          sudo apt-get update
          sudo apt-get install -y adb
          
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          
      - name: Download Termux APK
        run: |
          wget https://f-droid.org/repo/com.termux_1020.apk -O termux.apk
          
      - name: Start Android Emulator, Install Termux, and Run Script
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          script: |
            adb start-server
            adb devices  # Ensure the emulator is detected
            adb shell input keyevent 82  # Unlock screen
            adb install termux.apk       # Install Termux APK
            adb shell monkey -p com.termux -c android.intent.category.LAUNCHER 1  # Launch Termux
            sleep 5  # Wait for Termux to initialize
            
            # Grant Termux storage access using UI interaction
            adb shell am start -n com.termux/.TermuxActivity
            sleep 5  # Give Termux time to load
            adb shell input text "termux-setup-storage"
            adb shell input keyevent 66  # Press Enter
            sleep 10  # Ensure storage is granted

            # Push baserom to accessible storage
            adb push baserom.us.z64 /storage/emulated/0/
            sleep 5  # Ensure file is copied

            # Move file inside Termux
            adb shell input text "mv /storage/emulated/0/baserom.us.z64 \$HOME/"
            adb shell input keyevent 66  # Press Enter
            sleep 5  # Ensure file is moved
            
            # Update and install packages inside Termux
            adb shell input text "pkg upgrade -y"
            adb shell input keyevent 66  # Press Enter
            sleep 20  # Allow upgrade to complete

            adb shell input text "pkg remove libglvnd"
            adb shell input keyevent 66
            sleep 5
            
            adb shell input text "pkg install git wget make python getconf zip apksigner clang binutils libglvnd-dev aapt which"
            adb shell input keyevent 66
            sleep 30  # Give time for installation

            # Clone and build project
            adb shell input text "git clone --recursive https://github.com/ManIsCat2/sm64coopdx.git"
            adb shell input keyevent 66
            sleep 15

            adb shell input text "cp \$HOME/baserom.us.z64 \$HOME/sm64coopdx/"
            adb shell input keyevent 66
            sleep 5
            
            adb shell input text "cd sm64coopdx && make"
            adb shell input keyevent 66
            sleep 60  # Allow time for build

      - name: Get Build Results
        run: |
          adb pull /data/data/com.termux/files/home/sm64coopdx/build/us_pc/sm64coopdx.apk || echo "APK not found; continuing..."

      - name: Upload APK Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sm64coopdx.apk
          path: sm64coopdx.apk
          if-no-files-found: warn