name: Run Termux in Android Emulator

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ADB
        run: |
          sudo apt-get update
          sudo apt-get install -y adb

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Download Termux APK
        run: wget https://f-droid.org/repo/com.termux_1020.apk -O termux.apk

      - name: Start Android Emulator, Install Termux, and Run Script
        uses: reactivecircus/android-emulator-runner@v2.33.0
        with:
          api-level: 21
          script: |
            adb start-server
            adb devices

            # Install Termux
            adb install termux.apk

            # Launch Termux
            adb shell am start -n com.termux/.HomeActivity
            sleep 8  # Increased wait for bootstrap dialog

            # Simulate tapping "Allow" (adjust if needed)
            adb shell input tap 540 1700  
            sleep 2  # Wait for permissions to be granted


            # Grant storage permissions (older method)
            adb shell input text "termux-setup-storage"
            sleep 8
            # Simulate tapping "Allow" (adjust if needed)
            adb shell input tap 540 1700  
            sleep 2  # Wait for permissions to be granted
            
            # Push necessary files to Termux
            adb push baserom.us.z64 /data/data/com.termux/files/home/
            adb push setup_build.sh /data/data/com.termux/files/home/
            sleep 2

            # Verify that files exist on /sdcard/
            adb shell ls /data/data/com.termux/files/home/baserom.us.z64 && echo "baserom.us.z64 found" || echo "baserom.us.z64 NOT found!"
            adb shell ls /data/data/com.termux/files/home/setup_build.sh && echo "setup_build.sh found" || echo "setup_build.sh NOT found!"
            sleep 2
            
            adb shell "chmod +x setup_build.sh && ./setup_build.sh"
            sleep 1000  # Wait for <<< to complete

      - name: Get Build Results
        run: |
          adb shell ls /data/data/com.termux/files/home/sm64coopdx/build/us_pc/ && echo "Build directory exists" || echo "Build directory NOT found!"
          adb shell ls /data/data/com.termux/files/home/sm64coopdx/build/us_pc/sm64coopdx.apk && echo "APK found!" || echo "APK NOT found!"
          adb pull /data/data/com.termux/files/home/sm64coopdx/build/us_pc/sm64coopdx.apk || echo "APK not found"

      - name: Upload APK Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sm64coopdx.apk
          path: /data/data/com.termux/files/home/sm64coopdx/build/us_pc/sm64coopdx.apk
          if-no-files-found: warn