name: Run Termux in Docker

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull and Run Termux Docker
        run: |
          docker pull termux/termux-docker:latest
          docker run --rm -v $PWD:/data termux/termux-docker:latest sh -c "
            apt update && apt upgrade -y &&
            apt install -y git wget make python zip clang binutils &&
            cp /data/baserom.us.z64 /data/setup_build.sh /data/data/com.termux/files/home/ &&
            chmod +x /data/data/com.termux/files/home/setup_build.sh &&
            cd /data/data/com.termux/files/home &&
            ./setup_build.sh
          "

      - name: Get Build Results
        run: |
          ls sm64coopdx/build/us_pc/ && echo "Build directory exists" || echo "Build directory NOT found!"
          ls sm64coopdx/build/us_pc/sm64coopdx.apk && echo "APK found!" || echo "APK NOT found!"

      - name: Upload APK Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sm64coopdx.apk
          path: sm64coopdx/build/us_pc/sm64coopdx.apk
          if-no-files-found: warn