name: Termux SM64CoopDX Build

on: [push, pull_request]

jobs:
  termux-build:
    runs-on: ubuntu-latest
    container:
      image: termux/termux-docker:x86_64
      volumes:
        - ${{ github.workspace }}:/home/termux/work

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: /home/termux/work

      - name: Setup Environment
        run: |
          # Termux environment setup
          echo "Updating packages..."
          pkg update -y
          pkg install -y git make python clang binutils

      - name: Prepare SM64CoopDX
        run: |
          cd /home/termux
          git clone --recursive https://github.com/ManIsCat2/sm64coopdx.git
          cp work/baserom.us.z64 sm64coopdx/baserom.us.z64

      - name: Build ROM
        run: |
          cd /home/termux/sm64coopdx
          make -j$(nproc)

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sm64-build
          path: /home/termux/sm64coopdx/build